# tasky5.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
        - name: tasky
          image: 321213423920.dkr.ecr.us-east-1.amazonaws.com/wiz-containers:latest
          env:
          - name: SECRET_KEY
            value: "supercalifragilousexpialidocious"
          - name: MONGODB_URI
            value: "mongodb://wiz_db_user:wiz_db-password@192.168.25.192:27017/?authSource=wiz_db defaultauthdb=wiz_db"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: tasky
  namespace: traefik
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: tasky